javascripts: 
- base: 
  - prototype
  - effects
  - dragdrop
  - controls
  - sound
  - iyxzone
  - cookie
  - url
  - feed_delivery
  - dig
  - comment
  - facebox
  - report
  - in_place_editor_extension
  - emotion
  - friend
  - menu
  - chat
  - calendar_date_select/calendar_date_select
  - calendar_date_select/locale/cn
  - calendar_date_select/format_iso_date
  - production_config
  - mini_blog
  - guestbook
- register:
  - game
  - register
  - event.simulate
- home:
  - home
  - photo
  - video
  - status
- profile: 
  - profile
  - chinese_region
  - video
  - game
  - poke
  - setting
  - tag
  - event.simulate
- photo:
  - photo
  - textboxlist
  - cropper
- album:
  - album
- blog:
  - blog
  - yushan_nicEdit
  - textboxlist
- event:
  - game
  - event
- search:
  - game
  - search
  - idol
  - event.simulate
- game:
  - game
  - rating
  - video
  - tag
- guild:
  - photo
  - guild
- mail:
  - mail
  - emotion
  - textboxlist
- share:
  - share
  - video
- video:
  - video
  - textboxlist
- forum:
  - forum
  - yushan_nicEdit
- invitation:
  - event
  - guild
- request:
  - event
  - guild
stylesheets: 
- base: 
  - common
  - home
  - calendar_date_select/silver
- photo:
  - swfupload
  - cropper
