javascripts: 
- base: 
  - prototype
  - effects
  - dragdrop
  - controls
  - sound
  - iyxzone
  - cookie
  - url
  - feed_delivery
  - comment
  - facebox
  - in_place_editor_extension
  - emotion
  - friend
  - menu
  - chat
  - calendar_date_select/calendar_date_select
  - calendar_date_select/locale/cn
  - calendar_date_select/format_iso_date
  - production_config
  - mini_blog
- register:
  - game
  - register
  - event.simulate
- home:
  - home
  - photo
  - video
  - status
- profile: 
  - profile
  - chinese_region
  - video
  - game
  - event.simulate
- photo:
  - photo
  - textboxlist
  - cropper
- blog:
  - blog
  - yushan_nicEdit
  - textboxlist
- event:
  - game
  - event
- search:
  - game
  - search
  - idol
  - event.simulate
- game:
  - game
  - rating
  - video
- guild:
  - photo
  - guild
- mail:
  - mail
  - emotion
  - textboxlist
- share:
  - share
  - video
- video:
  - video
  - textboxlist
- forum:
  - forum
  - yushan_nicEdit
stylesheets: 
- base: 
  - common
  - home
  - calendar_date_select/silver
- photo:
  - swfupload
  - cropper
